-- Baseline PostgreSQL schema for the Dublin Bikes Spring Boot backend.
--
-- Translated from the Flask/Alembic migration history at
--   ucdse/flask-app/migrations/versions/
-- and reconciled against the JPA entities in
--   dev.kaiwen.bikes.model (station, availability, users, weather_forecast,
--   sessions, message_store).
--
-- Schema ownership note:
--   The legacy Flask stack ran on MySQL with Alembic. The backend now targets
--   PostgreSQL and Spring Boot owns the schema via Flyway. Hibernate runs in
--   `ddl-auto: validate` mode, so column names / types / nullability below
--   must stay in lock-step with the entities.
--
--   `message_store` is created here because Spring + Python `chat-service`
--   share the same database; LangChain `SQLChatMessageHistory` reads/writes
--   that table, Spring only treats it as opaque (no JPA entity).

-- =============================================================================
-- station: JCDecaux station metadata (natural key = station number from API)
-- =============================================================================
CREATE TABLE station (
    number        INTEGER       PRIMARY KEY,
    contract_name VARCHAR(50)   NOT NULL,
    name          VARCHAR(100)  NOT NULL,
    address       VARCHAR(200)  NOT NULL,
    latitude      REAL          NOT NULL,
    longitude     REAL          NOT NULL,
    banking       BOOLEAN       NOT NULL,
    bonus         BOOLEAN       NOT NULL,
    bike_stands   INTEGER       NOT NULL
);

-- =============================================================================
-- availability: per-scrape availability snapshots for each station
-- =============================================================================
CREATE TABLE availability (
    id                    INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number                INTEGER      NOT NULL,
    available_bikes       INTEGER      NOT NULL,
    available_bike_stands INTEGER      NOT NULL,
    status                VARCHAR(20)  NOT NULL,
    last_update           BIGINT       NOT NULL,
    "timestamp"           TIMESTAMP    NOT NULL,
    requested_at          TIMESTAMP    NOT NULL,
    CONSTRAINT fk_availability_station
        FOREIGN KEY (number) REFERENCES station (number) ON DELETE CASCADE
);

CREATE INDEX ix_availability_number    ON availability (number);
CREATE INDEX ix_availability_timestamp ON availability ("timestamp");

-- =============================================================================
-- users: registered accounts.
-- =============================================================================
CREATE TABLE users (
    id                                 INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                           VARCHAR(64)  NOT NULL,
    email                              VARCHAR(120) NOT NULL,
    password_hash                      VARCHAR(256) NOT NULL,
    avatar_url                         VARCHAR(255),
    is_active                          BOOLEAN      NOT NULL DEFAULT TRUE,
    email_verification_code            VARCHAR(6),
    email_verification_code_expires_at TIMESTAMP,
    email_verification_code_sent_at    TIMESTAMP,
    activation_token                   VARCHAR(64),
    token_version                      INTEGER      NOT NULL DEFAULT 0,
    created_at                         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                         TIMESTAMP
);

CREATE UNIQUE INDEX ix_users_username         ON users (username);
CREATE UNIQUE INDEX ix_users_email            ON users (email);
CREATE UNIQUE INDEX ix_users_activation_token ON users (activation_token);

-- Maintain users.updated_at on UPDATE. MySQL had `ON UPDATE CURRENT_TIMESTAMP`
-- and SQLAlchemy used `onupdate=func.now()` at the ORM layer. The Spring entity
-- marks updated_at as insertable=false / updatable=false, so we need a trigger
-- to keep it fresh.
CREATE OR REPLACE FUNCTION set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

-- =============================================================================
-- weather_forecast: hourly OpenWeatherMap forecast cache for Dublin
-- =============================================================================
CREATE TABLE weather_forecast (
    id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_time TIMESTAMP    NOT NULL,
    temperature   REAL         NOT NULL,
    weather_code  INTEGER      NOT NULL,
    description   VARCHAR(100),
    icon          VARCHAR(20),
    feels_like    REAL,
    pressure      INTEGER,
    humidity      INTEGER,
    uvi           REAL,
    clouds        INTEGER,
    visibility    INTEGER,
    wind_speed    REAL,
    wind_deg      INTEGER,
    pop           REAL         DEFAULT 0.0,
    fetched_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ix_weather_forecast_forecast_time
    ON weather_forecast (forecast_time);

-- =============================================================================
-- sessions: LLM chat session metadata. updated_at is maintained by the JPA
-- @PreUpdate hook in dev.kaiwen.bikes.model.ChatSession, so no DB trigger.
-- =============================================================================
CREATE TABLE sessions (
    id         VARCHAR(64)  PRIMARY KEY,
    user_id    INTEGER      NOT NULL,
    title      VARCHAR(100),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_sessions_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX ix_sessions_user_id ON sessions (user_id);

-- =============================================================================
-- message_store: LangChain SQLChatMessageHistory storage (Python chat-service
-- owns reads/writes). Spring does not map this table to a JPA entity.
-- =============================================================================
CREATE TABLE message_store (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    message    JSONB
);
